name: Chenyang Yuan's Homepage
description: Chenyang Yuan's research, software and projects
meta_description: "Chenyang Yuan's research, software and projects"

markdown: kramdown
highlighter: rogue
logo: false

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  research:
  software:
  projects:

# Details for the RSS feed generator
url:            'https://www.chenyang.co'
author:         'Chenyang Yuan'
