name: Chenyang Yuan's Homepage
description: Chenyang Yuan's research, software, tutorials and projects
meta_description: "Chenyang Yuan's research, software, tutorials and projects"

markdown: kramdown
highlighter: rouge
logo: false

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

plugins:
 - jekyll-paginate
 - jekyll-sitemap
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  research:
  software:
  projects:
  tutorials:
  papers:
  talks:

# Order for paper tabs
paper_venue_order:
 - Journal
 - Conference
 - Workshop
 - Preprint
 - Thesis

paper_category_order:
 - Theoretical Foundations of Diffusion Models
 - Global Landscape of Non-Convex Problems
 - AI for Engineering Design
 - Rounding Convex Relaxations of Quadratic Maps
 - Permanent Approximation
 - Control of Queueing Networks
 - Thesis
 - Misc Science

# Details for the RSS feed generator
url:            'https://www.chenyang.co'
author:         'Chenyang Yuan'
