name: Chenyang's Homepage
description: Projects and Blog
meta_description: "Projects and Blog"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'https://www.chenyang.co'
author:         'Chenyang Yuan'
